using Blastula.Collision;
using Blastula.VirtualVariables;
using Godot;
using static Blastula.BNodeFunctions;

namespace Blastula.Operations
{
    /// <summary>
    /// Set BNode data which is used by players or enemies when collisions occur, or change the collision layer.
    /// </summary>
    [GlobalClass]
    [Icon(Persistent.NODE_ICON_PATH + "/redCross.png")]
    public unsafe partial class SetCollisionData : Modifier
    {
        /// <summary>
        /// If nonempty, the name of the new bullet collision layer as generated by CollisionManager.
        /// </summary>
        [Export] public string newCollisionLayer = "";
        /// <summary>
        /// If nonempty, the new number to set the "graze" value in the BNode.
        /// </summary>
        [Export] public string graze = "";
        /// <summary>
        /// If nonempty, the new number to set the "power" value in the BNode.
        /// </summary>
        [Export] public string power = "";
        /// <summary>
        /// If nonempty, the new number to set the "health" value in the BNode.
        /// </summary>
        [Export] public string health = "";

        public override void ModifyStructure(int inStructure)
        {
            if (inStructure < 0 || inStructure >= mqSize) { return; }

            if (newCollisionLayer != null && newCollisionLayer != "")
            {
                int colLayerID = CollisionManager.GetBulletLayerIDFromName(newCollisionLayer);
                BNodeFunctions.SetColliderInfo(inStructure, colLayerID, masterQueue[inStructure].collisionSleepStatus.canSleep);
            }

            if (graze != null && graze != "")
            {
                masterQueue[inStructure].graze = Solve("graze").AsSingle();
            }

            if (power != null && power != "")
            {
                masterQueue[inStructure].power = Solve("power").AsSingle();
            }

            if (health != null && health != "")
            {
                masterQueue[inStructure].health = Solve("health").AsSingle();
            }
        }
    }
}

