using Blastula.Graphics;
using Blastula.VirtualVariables;
using Godot;

namespace Blastula.Operations
{
    /// <summary>
    /// Set the z-index (layering) of a bullet or laser graphic name,
    /// as generated by BulletRendererManager or LaserRendererManager.
    /// </summary>
    [GlobalClass]
    [Icon(Persistent.NODE_ICON_PATH + "/nova.png")]
    public unsafe partial class SetZIndex : Discrete
    {
        public enum GraphicType
        {
            Bullet, Laser
        }

        [Export] public GraphicType graphicType = GraphicType.Bullet;
        [Export] public string graphicName = "None";
        /// <summary>
        /// We expect an integer here. If it's not within the valid range for CanvasItems, it will be clamped.
        /// </summary>
        [Export] public string newZIndex = "0";

        public override void Run()
        {
            int zVal = Solve("newZIndex").AsInt32();
            switch (graphicType)
            {
                case GraphicType.Bullet:
                    BulletRenderer.ChangeZIndex(graphicName, zVal);
                    break;
                case GraphicType.Laser:
                    LaserRenderer.ChangeZIndex(graphicName, zVal);
                    break;
            }
        }
    }
}

